apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: time-slot-authentication-service-mongodb
  name: time-slot-authentication-service-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: time-slot-authentication-service-mongodb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: time-slot-authentication-service-mongodb
    spec:
      containers:
      - image: mongo
        imagePullPolicy: ""
        name: time-slot-authentication-service-mongodb
        resources: {}
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/
          name: authentication-service-mongodb-storage
        - mountPath: /data/db/
          name: authentication-service-mongodb-storage-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: authentication-service-mongodb-storage
          hostPath:
            path: /run/desktop/mnt/host/c/denis/time-slot-booking/seed/authentication-service-mongodb
            type: Directory
        - name: authentication-service-mongodb-storage-data
          hostPath:
            path: /run/desktop/mnt/host/c/denis/time-slot-booking/data/authentication-service-mongodb
            type: DirectoryOrCreate
status: {}
