apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: time-slot-calendar-service
  name: time-slot-calendar-service
spec:
  ports:
  - name: "6500"
    port: 6500
    targetPort: 6500
  selector:
    io.kompose.service: time-slot-calendar-service
status:
  loadBalancer: {}
