apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: time-slot-account-service-mongodb
  name: time-slot-account-service-mongodb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27016
  selector:
    io.kompose.service: time-slot-account-service-mongodb
status:
  loadBalancer: {}
