apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: time-slot-account-service
  name: time-slot-account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: time-slot-account-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: time-slot-account-service
    spec:
      containers:
      - image: denisbalan/time-slot-account-service
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - netstat -tulpn | grep LISTEN
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 5
        name: time-slot-account-service
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
