spring:
  data:
    mongodb:
      host: time-slot-authentication-service-mongodb
      username: user
      password: user123456
      database: authentication-database
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
