security:
  oauth2:
    client:
      clientId: notification-service
      clientSecret: user123456
      accessTokenUri: http://time-slot-authentication-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /notifications
  port: 8000

feign:
  hystrix:
    enabled: true
    
remind:
  cron: 0 0 0 * * *
  email:
    text: "Hey, {0}! You have some pending time-slots."
    subject: Timeslot reminder

backup:
  cron: 0 0 12 * * *
  email:
    text: "Howdy, {0}. Your account backup is ready."
    subject: Timeslot account backup
    attachment: backup.json

spring:
  data:
    mongodb:
      host: time-slot-notification-service-mongodb
      username: user
      password: user123456
      database: notification-database
      port: 27017
  mail:
    host: smtp.gmail.com
    port: 465
    username: dev-user
    password: dev-password
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true
