trigger:
  branches:
    include:
      - feature/*
      - main
  paths:
    exclude:
      - README.*
      
parameters:
- name: 'folders'
  type: object
  default:
   - configuration
   - eureka-registry

variables:
  tag: 'latest'
  dockerHub: 'docker-denisbalan'

stages:
  - stage: Build_all
    jobs:
      - job: Init
        displayName: Init
        steps:
          - pwsh: |     
              Write-Host "Init"
            displayName: Init
      - ${{each folderName in parameters.folders}}:
        - template: deploy.yml
          parameters:
            dockerHub: '$(dockerHub)'
            tag: '$(tag)'
            imageName: 'time-slot-$(folderName)'
            folderName: '$(folderName)'
    # jobs:
        # - template: deploy.yml
          # parameters:
            # dockerHub: '$(dockerHub)'
            # tag: '$(tag)'
            # imageName: 'time-slot-${{ parameters.folders }}'
            # folderName: 'src/${{ parameters.folders }}'