trigger:
  branches:
    include:
      - feature/*
      - main
  paths:
    exclude:
      - README.*

resources:
- repo: self

variables:
  tag: 'latest'
  dockerHub: 'docker-denisbalan'
  folderName: 'configuration'
  name: 'static-build'

stages:
  - stage: Build_all
    jobs:
      - job: Init
        displayName: Init
        steps:
          - pwsh: |     
              Write-Host "Init"
              find | sed 's|[^/]*/|- |g'
            displayName: Init
      - template: deploy.yml
        parameters:
          dockerHub: '$(dockerHub)'
          tag: '$(tag)'
          imageName: 'time-slot-$(folderName)'
          folderName: '$(folderName)'
          name: '$(name)'