trigger:
  branches:
    include:
      - feature/*
      - main
  paths:
    exclude:
      - README.*
      
parameters:
- name: 'folders'
  type: object
  default: 
    - configuration
    - eureka-registry

variables:
  tag: 'latest'
  dockerHub: 'docker-denisbalan'
  
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build all
    jobs:
      - ${{each folderName in parameters.folders}}:
        - template: deploy.yml
          parameters:
            dockerHub: '$(dockerHub)'
            tag: '$(tag)'
            imageName: 'time-slot-$(folderName)'
            folderName: 'src/$(folderName)'