parameters:
  dockerHub: ''
  tag: ''
  imageName: ''
  folderName: ''

jobs:  
  - deployment: Build and push
    displayName: 'Build docker image $(imageName)'
    variables: 
      - ${{ parameters }}
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'dev'
        strategy: 
          runOnce: 
            deploy:
              steps:
                - task: Docker@2
                  displayName: 'Build locally image $(imageName)'
                  inputs:
                    containerRegistry: '$(dockerHub)'
                    repository: '$(imageName)'
                    command: 'build'
                    Dockerfile: '**/$(folderName)/Dockerfile'
                    buildContext: '**/$(folderName)/'
                    tags: '$(tag)'
                - task: Docker@2
                  displayName: 'Push image $(imageName)'
                  inputs:
                    containerRegistry: '$(dockerHub)'
                    repository: '$(imageName)'
                    command: 'push'
                    tags: |
                      $(tag)