parameters:
  dockerHub: ''
  tag: ''
  imageName: ''
  folderName: ''

variables:
  dockerHub: '${{ parameters.dockerHub }}'
  tag: '${{ parameters.tag }}'
  imageName: '${{ parameters.imageName }}'
  folderName: '${{ parameters.folderName }}'

jobs:  
- job: Build and push
  displayName: 'Build docker image $(imageName)'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    displayName: 'Build locally image $(imageName)'
    inputs:
      containerRegistry: '$(dockerHub)'
      repository: '$(imageName)'
      command: 'build'
      Dockerfile: '**/$(folderName)/Dockerfile'
      buildContext: '**/$(folderName)/'
      tags: '$(tag)'
  - task: Docker@2
    displayName: 'Push image $(imageName)'
    inputs:
      containerRegistry: '$(dockerHub)'
      repository: '$(imageName)'
      command: 'push'
      tags: |
        $(tag)